create table tb_sales (id int8 generated by default as identity, amount float8, date date, deals int4, visited int4, seller_id int8, primary key (id));
create table tb_sellers (id int8 generated by default as identity, name varchar(255), primary key (id));
alter table if exists tb_sales add constraint FKp0nn0oixeiw2fq3jivj6vnsu foreign key (seller_id) references tb_sellers;




postgres://qlriwtvdsuyhnv
:
7c03c33463e0b664a7d7140e3f1cc3a8a2eb7494b27474859b2babe155a87789
@
ec2-54-87-112-29.compute-1.amazonaws.com
:5432
/d8nh9k67pads